baseurl = "https://blog.hoetzel.info/"
theme= "m10c"
# theme="ananke"
pygmentsCodeFences=true
pygmentsStyle="solarized-dark"
# PygmentsCodeFences = true
# pygmentsUseClassic=true
# solarizeddark
pygmentsstyle = "solarizedlight"
ignoreFiles = [ "\\.html" ]
# disqusShortname = "juergenhoetzel"

[params]
    DateForm = "2.1.2006"
    themecolor = "green"
    author = "Jürgen Hötzel"
    # subtitle = "a minimal theme for ~~Ghost~~ Hugo"
    name = "Jürgen Hötzel"
    bio = "I code in Emacs on Arch Linux with my bare hands"
    description = "Musings about Emacs, Arch Linux 🐧 and Crypto 🔑"
    twitter = "juergenhoetzel"
    stackoverflow = "users/308679"
    github = "juergenhoetzel"

